SOURCES += \
	$$P_SOURCES_COMMON_EMULATORS/Z80.c \
	"$$P_SOURCES_COMMON_EMULATORS/ZX Spectrum.c" \

HEADERS += \
	$$P_SOURCES_COMMON_EMULATORS/Z80.h \
	"$$P_SOURCES_COMMON_EMULATORS/ZX Spectrum.h" \
	$$P_SOURCES_COMMON_EMULATORS/MachineABI.h \
